Repository 4-Image-Module/Image-Module, pull requests merged in 2024-10, with the labels that each got.

#8 Init: Upload Server Init
  upload/.gitignore
  upload/build.gradle
  upload/gradle/wrapper/gradle-wrapper.jar
  upload/gradle/wrapper/gradle-wrapper.properties
  upload/gradlew
  upload/gradlew.bat
  upload/settings.gradle
  upload/src/main/java/image/module/upload/UploadApplication.java
  upload/src/main/resources/application.yml
  upload/src/test/java/image/module/upload/UploadApplicationTests.java
Labels: feat💫

#12 Feat: #11 이미지 업로드 및 다운로드
  docker-compose.yml
  internal/build.gradle
  internal/src/main/java/image/module/internal/config/MinioConfig.java
  internal/src/main/java/image/module/internal/controller/ImageController.java
  internal/src/main/java/image/module/internal/service/ImageService.java
  internal/src/main/resources/application.properties
  internal/src/main/resources/application.yml
Labels: feat💫

#13 Feature:#10 image upload
  upload/build.gradle
  upload/src/main/java/image/module/upload/ImageRepository.java
  upload/src/main/java/image/module/upload/UploadApplication.java
  upload/src/main/java/image/module/upload/UploadConfig.java
  upload/src/main/java/image/module/upload/UploadController.java
  upload/src/main/java/image/module/upload/UploadService.java
  upload/src/main/java/image/module/upload/domain/BaseEntity.java
  upload/src/main/java/image/module/upload/domain/Image.java
  upload/src/main/resources/application.yml
Labels: feat💫

#15 Init: #14 CDN server 생성 및 설정
  cdn/.gitignore
  cdn/build.gradle
  cdn/gradle/wrapper/gradle-wrapper.jar
  cdn/gradle/wrapper/gradle-wrapper.properties
  cdn/gradlew
  cdn/gradlew.bat
  cdn/settings.gradle
  cdn/src/main/java/image/module/cdn/CdnApplication.java
  cdn/src/main/resources/application.yml
  cdn/src/test/java/image/module/cdn/CdnApplicationTests.java
Labels: init

#22 Feat: #17 Kafka 기본 구현
  docker-compose.yml
  internal/build.gradle
  internal/src/main/java/image/module/internal/ConsumerApplicationKafkaConfig.java
  internal/src/main/java/image/module/internal/ConsumerService.java
  internal/src/main/resources/application.yml
  upload/build.gradle
  upload/src/main/java/image/module/upload/ProducerApplicationKafkaConfig.java
  upload/src/main/java/image/module/upload/UploadService.java
  upload/src/main/resources/application.yml
Labels: feat💫

#18 Feat: #16 원본 이미지 WebP로 변환 후 업로드
  internal/build.gradle
  internal/src/main/java/image/module/internal/ConsumerService.java
  internal/src/main/java/image/module/internal/config/ConsumerApplicationKafkaConfig.java
  internal/src/main/java/image/module/internal/controller/ImageController.java
  internal/src/main/java/image/module/internal/service/ImageService.java
  internal/src/main/resources/application.yml
Labels: feat💫

#27 Feat: #20 cdn url 생성
  data/src/main/java/image/module/data/domain/Image.java
  upload/src/main/java/image/module/upload/application/ImageRequest.java
  upload/src/main/java/image/module/upload/application/UploadService.java
  upload/src/main/java/image/module/upload/infrastructure/DataClient.java
  upload/src/main/java/image/module/upload/infrastructure/DataService.java
  upload/src/main/resources/application.yml
Labels: feat💫

#31 Feat: #19 cdn basic feature 구현
  cdn/src/main/java/image/module/cdn/CdnApplication.java
  cdn/src/main/java/image/module/cdn/client/UrlServiceClient.java
  cdn/src/main/java/image/module/cdn/config/RedisConfig.java
  cdn/src/main/java/image/module/cdn/controller/CdnController.java
  cdn/src/main/java/image/module/cdn/dto/ImageDto.java
  cdn/src/main/java/image/module/cdn/dto/ImageResponseDto.java
  cdn/src/main/java/image/module/cdn/service/CdnService.java
  cdn/src/main/java/image/module/cdn/service/RedisService.java
  cdn/src/main/resources/application.yml
  eureka/src/main/java/image/module/eureka/EurekaApplication.java
Labels: feat💫

#30 Feature/#25 check extension
  data/src/main/java/image/module/data/application/ImageService.java
  upload/build.gradle
  upload/src/main/java/image/module/upload/UploadApplication.java
  upload/src/main/java/image/module/upload/application/ImageRequest.java
  upload/src/main/java/image/module/upload/application/UploadService.java
  upload/src/main/java/image/module/upload/domain/ImageExtension.java
  upload/src/main/java/image/module/upload/util/FileUtil.java
  upload/src/main/resources/application.yml
Labels: feat💫

#37 Feat/#29 이미지 리사이징, DB에 저장
  data/.gitignore
  data/src/main/java/image/module/data/application/ImageService.java
  data/src/main/java/image/module/data/domain/Image.java
  data/src/main/java/image/module/data/domain/repository/ImageRepository.java
  data/src/main/java/image/module/data/presentation/ImageController.java
  eureka/.gitignore
  internal/build.gradle
  internal/src/main/java/image/module/internal/DataClient.java
  internal/src/main/java/image/module/internal/InternalApplication.java
  internal/src/main/java/image/module/internal/dto/ImageRequest.java
  internal/src/main/java/image/module/internal/service/ImageService.java
  internal/src/main/resources/application.yml
  upload/src/main/java/image/module/upload/application/UploadService.java
  upload/src/main/resources/application.yml
Labels: feat💫

#42 Feat: #40 upload 응답 관련
  upload/build.gradle
  upload/src/main/java/image/module/upload/application/UploadService.java
  upload/src/main/java/image/module/upload/presentation/UploadController.java
  upload/src/main/resources/application.yml
Labels: feat💫

#44 Feat: #32 cdn caching 구현
  cdn/src/main/java/image/module/cdn/config/RedisConfig.java
  cdn/src/main/java/image/module/cdn/config/RedisExpirationListener.java
  cdn/src/main/java/image/module/cdn/service/CdnService.java
  cdn/src/main/java/image/module/cdn/service/RedisService.java
Labels: feat💫

#49 Feat : #45 feign client 설정
  cdn/src/main/java/image/module/cdn/client/UrlServiceClient.java
  cdn/src/main/java/image/module/cdn/dto/ImageDto.java
  cdn/src/main/java/image/module/cdn/service/CdnService.java
  cdn/src/main/java/image/module/cdn/service/RedisService.java
  gateway/src/main/resources/application.yml
  url/src/main/java/image/module/url/dto/ImageDto.java
Labels: feat💫

#56 Feat: #50 CDN 이미지 반환 기능 구현
  cdn/src/main/java/image/module/cdn/client/UrlServiceClient.java
  cdn/src/main/java/image/module/cdn/dto/ImageDto.java
  cdn/src/main/java/image/module/cdn/service/CdnService.java
  cdn/src/main/java/image/module/cdn/service/RedisService.java
  url/src/main/java/image/module/url/controller/UrlController.java
  url/src/main/java/image/module/url/dto/ImageDto.java
  url/src/main/java/image/module/url/service/UrlService.java
Labels: feat💫

#59 !HOTFIX: #58 kafka 오류 해결 & minio url 하드코딩
  docker-compose.yml
  internal/src/main/java/image/module/internal/config/ConsumerApplicationKafkaConfig.java
  internal/src/main/java/image/module/internal/config/MinioConfig.java
  internal/src/main/resources/application-dev.yml
  upload/src/main/java/image/module/upload/config/ProducerApplicationKafkaConfig.java
  upload/src/main/java/image/module/upload/config/UploadConfig.java
  upload/src/main/resources/application.yml
  url/src/main/java/image/module/url/config/MinioConfig.java
Labels: bug

#63 Init: #57 convertSever init
  convert/.gitattributes
  convert/.gitignore
  convert/build.gradle
  convert/gradle/wrapper/gradle-wrapper.jar
  convert/gradle/wrapper/gradle-wrapper.properties
  convert/gradlew
  convert/gradlew.bat
  convert/settings.gradle
  convert/src/main/java/image/module/convert/ConvertApplication.java
  convert/src/main/resources/application-dev.yml
  convert/src/main/resources/application-prod.yml
  convert/src/main/resources/application.yml
  convert/src/test/java/image/module/convert/ConvertApplicationTests.java
  docker-compose.yml
Labels: init

#65 Feature/#60 upload - size,cahingTime
  data/src/main/java/image/module/data/application/ImageResponse.java
  data/src/main/java/image/module/data/application/ImageService.java
  data/src/main/java/image/module/data/domain/Image.java
  data/src/main/java/image/module/data/presentation/ImageController.java
  data/src/main/java/image/module/data/presentation/ImageRequest.java
  upload/src/main/java/image/module/upload/application/ImageRequest.java
  upload/src/main/java/image/module/upload/application/ImageResponse.java
  upload/src/main/java/image/module/upload/application/ImageUploadMessage.java
  upload/src/main/java/image/module/upload/application/UploadService.java
  upload/src/main/java/image/module/upload/presentation/UploadController.java
  upload/src/main/resources/application.yml
Labels: feat💫

#73 FEAT: #67 이미지 다건 업로드 multi upload
  upload/src/main/java/image/module/upload/application/UploadService.java
  upload/src/main/java/image/module/upload/presentation/UploadController.java
Labels: feat💫

#75 Feat: #66 cdn 고급 기능 구현
  cdn/src/main/java/image/module/cdn/CdnApplication.java
  cdn/src/main/java/image/module/cdn/client/UrlServiceClient.java
  cdn/src/main/java/image/module/cdn/config/RedisConfig.java
  cdn/src/main/java/image/module/cdn/config/RedisExpirationListener.java
  cdn/src/main/java/image/module/cdn/dto/ImageDto.java
  cdn/src/main/java/image/module/cdn/service/CdnService.java
  cdn/src/main/java/image/module/cdn/service/RedisService.java
  cdn/src/main/resources/application-prod.yml
  cdn/src/main/resources/application.yml
  docker-compose.yml
Labels: feat💫

#78 Feat/#77 resize and minio upload
  convert/src/main/java/image/module/convert/service/ImageService.java
  docker-compose.yml
  resize/src/main/java/image/module/resize/config/MinioConfig.java
  resize/src/main/java/image/module/resize/service/ResizeService.java
Labels: feat💫

#80 Feat: #79-리사이징 된 데이터 DB 저장 성공
  data/src/main/java/image/module/data/application/ImageService.java
  data/src/main/java/image/module/data/domain/Image.java
  data/src/main/java/image/module/data/presentation/CreateResizeRequest.java
  data/src/main/java/image/module/data/presentation/ImageController.java
  resize/build.gradle
  resize/src/main/java/image/module/resize/DataClient.java
  resize/src/main/java/image/module/resize/dto/CreateResizeRequest.java
  resize/src/main/java/image/module/resize/service/ResizeService.java
Labels: feat💫

#90 FIX: #87 현재 시간 설정
  data/src/main/java/image/module/data/domain/BaseEntity.java
  data/src/main/resources/application-prod.yml
  upload/src/main/java/image/module/upload/application/UploadService.java
Labels: fix

#88 Refactor/#86 원본 size 수정하는 로직 삭제
  convert/src/main/java/image/module/convert/dto/UpdateImageData.java
  convert/src/main/java/image/module/convert/service/ImageService.java
  data/src/main/java/image/module/data/application/ImageService.java
  data/src/main/java/image/module/data/domain/Image.java
  data/src/main/java/image/module/data/presentation/ImageController.java
  data/src/main/java/image/module/data/presentation/UpdateImageData.java
  resize/src/main/java/image/module/resize/service/ResizeService.java
Labels: fix

#92 Feat: #89- 메타데이터 삭제 시 이미지 회전 문제 해결
  convert/build.gradle
  convert/src/main/java/image/module/convert/dto/OriginalImageResponse.java
  convert/src/main/java/image/module/convert/service/ImageService.java
Labels: feat💫

#94 Fix: #89-yml 수정
  convert/src/main/resources/application.yml
Labels: fix

#95 Feat : #93 cdn advance second
  cdn/src/main/java/image/module/cdn/config/RedisExpirationListener.java
  cdn/src/main/java/image/module/cdn/controller/CdnController.java
  cdn/src/main/java/image/module/cdn/service/CdnService.java
  cdn/src/main/java/image/module/cdn/service/RedisService.java
  url/src/main/java/image/module/url/service/UrlService.java
Labels: feat💫

#98 Refactor/#96 전체적인 메서드 이름 명시적으로 변경
  convert/src/main/java/image/module/convert/DataClient.java
  convert/src/main/java/image/module/convert/dto/OriginalFileInfo.java
  convert/src/main/java/image/module/convert/service/ConvertService.java
  data/src/main/java/image/module/data/application/ImageService.java
  data/src/main/java/image/module/data/domain/Image.java
  data/src/main/java/image/module/data/presentation/ImageController.java
  data/src/main/java/image/module/data/presentation/OriginalFileInfo.java
  data/src/main/java/image/module/data/presentation/ResizeRequestDto.java
  resize/src/main/java/image/module/resize/DataClient.java
  resize/src/main/java/image/module/resize/dto/ResizeRequestDto.java
  resize/src/main/java/image/module/resize/service/ResizeService.java
Labels: fix
